- name: Enable plugins
  ansible.builtin.command:
    cmd: "microk8s.enable {{ microk8s_plugin.key }}"
  with_dict: "{{ microk8s_plugins }}"
  loop_control:
    loop_var: microk8s_plugin
    label: "{{ microk8s_plugin.key }}"
  when:
  - microk8s_plugins is defined
  - microk8s_plugin.value
  - microk8s_plugin.key != "registry"
  - microk8s_plugin.key != "dns"
  register: microk8s_cmd_result
  changed_when:
  - "'Addon {{ microk8s_plugin.key }} is already enabled' not in microk8s_cmd_result.stdout"
  tags:
  - molecule-idempotence-notest
  - microk8s
  - microk8s.plugins
  - microk8s.plugins.enable

- name: Disable plugins
  ansible.builtin.command:
    cmd: "microk8s.disable {{ microk8s_plugin.key }}"
  with_dict: "{{ microk8s_plugins | default({}) }}"
  loop_control:
    loop_var: microk8s_plugin
    label: "{{ microk8s_plugin.key }}"
  register: microk8s_cmd_result
  changed_when:
  - "'Addon {{ microk8s_plugin.key }} is already disabled' not in microk8s_cmd_result.stdout"
  when:
  - microk8s_plugins is defined
  - not (microk8s_plugin.value | bool)
  - microk8s_plugin.key != "registry"
  tags:
  - molecule-idempotence-notest
  - microk8s
  - microk8s.plugins
  - microk8s.plugins.disable

- name: Enable registry
  ansible.builtin.command:
    cmd: "microk8s.enable registry:size={{ microk8s_registry_size }}"
  register: microk8s_cmd_result
  changed_when:
  - "'Addon registry is already enabled' not in microk8s_cmd_result.stdout"
  when:
  - microk8s_plugins is defined
  - microk8s_plugins.registry is defined
  - (microk8s_plugins.registry | bool)
  tags:
  - microk8s
  - microk8s.plugins
  - microk8s.plugins.enable
  - microk8s.plugins.enable.registry

- name: Disable registry
  ansible.builtin.command:
    cmd: "microk8s.disable registry:size={{ microk8s_registry_size }}"
  register: microk8s_cmd_result
  changed_when:
  - "'Addon registry is already disabled' not in microk8s_cmd_result.stdout"
  when:
  - microk8s_plugins is defined
  - microk8s_plugins.registry is defined
  - not (microk8s_plugins.registry | bool)
  tags:
  - microk8s
  - microk8s.plugins
  - microk8s.plugins.disable
  - microk8s.plugins.disable.registry

- name: Enable DNS
  ansible.builtin.command:
    cmd: 'microk8s.enable dns:{{ microk8s_dns_servers | join(",") }}'
  register: microk8s_cmd_result
  changed_when:
  - "'Addon dns is already enabled' not in microk8s_cmd_result.stdout"
  when:
  - microk8s_plugins is defined
  - microk8s_plugins.dns is defined
  - (microk8s_plugins.dns | bool)
  tags:
  - microk8s
  - microk8s.plugins
  - microk8s.plugins.enable
  - microk8s.plugins.enable.dns
